from fastapi import FastAPI, Query, HTTPException
from typing import List
import pandas as pd
import logging

app = FastAPI()

# Configurar logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def load_data(file_path: str) -> pd.DataFrame:
    """Carrega dados do arquivo CSV."""
    try:
        data = pd.read_csv(file_path, encoding="utf-8")
        logger.info("Dados carregados com sucesso.")
        return data
    except Exception as e:
        logger.error(f"Erro ao carregar o CSV: {e}")
        raise RuntimeError(f"Erro ao carregar o CSV: {e}")

data = load_data("Rol_Procedimentos.csv")

def search_operadoras(query: str, limit: int = 10) -> List[dict]:
    """Busca operadoras pelo nome fantasia."""
    try:
        resultados = data[data["nome_fantasia"].str.contains(query, case=False, na=False)]
        return resultados.head(limit).to_dict(orient="records")
    except Exception as e:
        logger.error(f"Erro ao processar a consulta: {e}")
        raise HTTPException(status_code=500, detail=f"Erro ao processar a consulta: {e}")

@app.get("/search", summary="Buscar operadoras", description="Busca operadoras pelo nome fantasia.")
def search(q: str = Query(..., title="Termo de busca", description="Termo para buscar no nome fantasia das operadoras"), limit: int = 10):
    """Rota para buscar operadoras pelo nome fantasia."""
    return search_operadoras(q, limit)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
